"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.15.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
# import dj_database_url
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-w3sg0-q!068e@h5w8(d66b+&zv3$6s!8ma&cefh8n$082frjb_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'website',
    'accounts',
    'movie',
]
# Rest config classes must be added 
REST_FRAMEWORK = {
  
    "DEFAULT_PERMISSION_CLASSES": [
      #AllowAny makes default permision class is_authenticated inactive or the same unrestricted for production 
        "rest_framework.permissions.AllowAny",  
    ], 

    # "DEFAULT_AUTHENTICATION_CLASSES": [
    #   "rest_framework.authentication.SessionAuthentication",
    #   "rest_framework.authentication.TokenAuthentication",
    # ],

    # 'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema', # drf_spectacular setting
   
}



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR/'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}




AUTH_USER_MODEL = "accounts.GFG" #phoneauthentication in accounts



#1-external connect key render.com postgres services
#  postgresql://movico_db_user:PMtpcF5qu6UP5NyVVsVXNelLRbVhuoPd@dpg-ctqheelsvqrc73cob8gg-a.oregon-postgres.render.com/movico_db

# 2-pip install dj-database-url then import in here 
# pip install psycopg2-binary
# pip install gunicorn 

# 3-overite db sqllite to postgres with the external key and * Then Migrate
# DATABASES['default'] = dj_database_url.parse(
#     'postgresql://movico_db_user:PMtpcF5qu6UP5NyVVsVXNelLRbVhuoPd@dpg-ctqheelsvqrc73cob8gg-a.oregon-postgres.render.com/movico_db',
#     conn_max_age=600,
#     conn_health_checks=True,
# )





# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR/"static/"

STATICFILES_DIRS = [
    BASE_DIR / "staticfiles",
    
]


MEDIA_URL = 'media/'
MEDIA_ROOT= BASE_DIR /"media/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
